// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from '@/components/Navbar';
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        {children}
        <footer className="bg-gray-950 py-12 text-center text-sm text-gray-400">
          <p>&copy; {new Date().getFullYear()} Robot Twitter Agency. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}